micronutrientsupport/database-architecture

- db/objects/country/R__view_country.sql
Creates a country view which returns a GeoJSON geometry for consumption by the API.
See #38 for limitations of this approach, but suggest we merge for now and re-address later
> feat: Create view for country table returning GeoJSON geometries

- db/objects/household/V0.1.0.40__household.sql
Added 'altitude_in_metres' column to household table. Simple as that.
> Add altitude column to household table

- db/objects/Biomarker/V0.1.0.600__Biomarker_measurement.sql
- db/objects/V0.1.0.500__Household_member.sql
-  allow values greater than 999 for biomarker_measurement.rbc_folate
- change datatype of household_member.survey_cluster to text
> Issue 168 update rbc folate precision

- db/objects/V0.1.0.35__survey.sql
Add new column 'survey_type' to survey with check constraint.
> Add survey type to survey

- db/dictionary-data/V0.2.0.710__biomarker_thresholds.sql
A minor change to remove duplicates form the insert script for this table.
> Remove duplicates from biomarker_threshold

- db/objects/Biomarker/V0.1.0.600__Biomarker_measurement.sql
- db/objects/Biomarker/V0.1.0.916__biomarker_import_vol.sql
- db/objects/Biomarker/V0.1.0.917__bad_biomarker_vals_view.sql
Small changes include:
- add selenium biomarker to db objects
- change upper threshold for reasonable range for rbc_folate after feedback
> 187 biomarker loader

- db/objects/R__105__RefreshAllMaterializedViews.sql
Adds function that refreshes all materialized views in a given schema.
This function is then ran at the end of the python pipeline.
> function refreshAllMaterializedViews

- db/afterVersioned__MaterializedViews.sql
- db/objects/intervention_costings/R__100_interventions-list.sql
- db/objects/intervention_costings/R__108_create_derived_intervention.sql
Creates a new record in the intervention table with data copied from the provided intervention id
Duplicates all rows from the intervention_data table with the intervention_id of the new intervention
> feat: add function for creating new intervention and duplicating parent data rows

- db/objects/R__074_survey_member_count.sql
- db/objects/R__075_top20_mn_per_household_survey.sql
update top20 household food chart to show consumption per average AFE rather than cumulative for the whole surveyed population
> fix: top20 food items household view availability values

- db/objects/Biomarker/R__100_biomarker_summary.sql
still include biomarker data that does not match a given aggregation area (data can still be aggregated by other fields)
> fix: biomarker view selection tweak

- db/objects/intervention_costings/V0.1.0.211__intervention_data.sql
A simple additional column to indicate whether the row is editable by users via front end.
Corresponding script changes are included in a matching branch on the db-test-data project.
> Add is_user_editable column to intervention_data table

- db/functions/V0.0.03__update_intervention_data_totals.sql
- db/objects/intervention_costings/R__110_fortificant_amount_totals.sql
Additional formula for row 28 of costing model spreadsheets as supplied by Katie.
New model spreadsheets with corresponding changes added to db-test-data repo.
I also fixed a minor bug in another formula and updated the fortificant view.
Closes #280
> Add New Formula for Costing Models

- db/objects/Biomarker/R__100_biomarker_summary.sql
> feat: add smoker status and altitude to biomarker summary view

- db/objects/intervention_costings/R__111_intervention-summary-costs.sql
> fix; fix typo in intervention costing view

- db/objects/V0.1.0.757__household_fct_list.sql
- db/objects/household/V0.1.0.46__household_fct_list.sql
> Andan fct match tweaks

- db/objects/R__089_monthly_food.sql
> chore: fix typo

- db/objects/intervention_costings/R__100_interventions-list.sql
- db/objects/intervention_costings/R__108_create_derived_intervention.sql
- db/objects/intervention_costings/V0.1.0.210__intervention.sql
- db/objects/intervention_costings/V0.1.0.218__intervention_updated_timestamp_trigger.sql
> feat: add last updated field to intervention and update trigger to intervetion_data

- db/dictionary-data/V0.2.0.550__micronutrients-data.sql
> fix: update micronutirent names in micronutrient dictionary

- db/db-config/V0.0.0.3__data-version.sql
> feat: add table for storing data semvar details

- .github/workflows/release-please.yml
> feat: add github actions for release please

- db/objects/intervention_costings/R__106_intervention-susu-costs.sql
- db/objects/intervention_costings/R__107_intervention-recurring-costs.sql
> fix: add ordering to other intervention json views:

- db/dictionary-data/intervention_costings/V0.2.0.551__fortificant.sql
> fix: disable foritifcant for now

- db/objects/R__060_diet_data_sources.sql
> fix: simplify diet datasource view naming

- CHANGELOG.md
- db/db-config/V0.0.0.4__data-version-populate.sql
- db/objects/R__060_diet_data_sources.sql
- db/objects/household/R__019_afe_ear_threshold.sql
> Release to main

- db/objects/intervention_costings/R__102_intervention-vehicle-standard.sql
- db/objects/intervention_costings/R__103_intervention-values-json.sql
> Andan intervention hotfix

- db/functions/V0.0.031__get_intervention_data_as_json.sql
Used chatgpt to rewrite it with fewer string concatenation operations. Speedup of ~10x
> refactor get_intervention_data_as_json()

- db/objects/intervention_costings/R__103_intervention-values-json.sql
- db/objects/intervention_costings/R__106_intervention-susu-costs.sql
- db/objects/intervention_costings/R__107_intervention-recurring-costs.sql
> Intervention data views fixes

- db/objects/household/R__199_household_details.sql
- db/objects/intervention_costings/R__108_create_derived_intervention.sql
- db/objects/intervention_costings/V0.1.0.230_fortifiable_foods.sql
> fix: add missing updates

- db/objects/intervention_costings/R__102_intervention-vehicle-standard.sql
- db/objects/intervention_costings/R__103_intervention-values-json.sql
- db/objects/intervention_costings/R__108_create_derived_intervention.sql
- db/objects/intervention_costings/V0.1.0.211__intervention_data.sql
> fix: source field for intervention data

- db/objects/V0.1.0.757__household_fct_list.sql
- db/objects/food_matching/V0.2.0.804__match_fct_micronutrients.sql
> fix: update fct match

- db/objects/V0.1.0.757__household_fct_list.sql
> fix: fix typo

- db/objects/V0.1.0.757__household_fct_list.sql
- db/objects/food_matching/V0.2.0.804__match_fct_micronutrients.sql
- db/objects/intervention_costings/R__107_intervention-recurring-costs.sql
- db/objects/intervention_costings/R__111_intervention-summary-costs.sql
> fix: tweak household matching, intervention data fixes

- db/objects/R__089_monthly_food.sql
- db/objects/V0.1.0.757__household_fct_list.sql
- db/objects/food_matching/V0.2.0.804__match_fct_micronutrients.sql
- db/objects/intervention_costings/R__107_intervention-recurring-costs.sql
- db/objects/intervention_costings/R__111_intervention-summary-costs.sql
> Andan intervention formula susu recurring
